version: '3'
services:

  db:
    container_name: postgres
    image: postgres:latest
    volumes:
      - /tmp/pgdata:/var/lib/postgresql/data/pgdata
      - ./ddl/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
      - ./ddl/test_data.sql:/docker-entrypoint-initdb.d/test_data.sql
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=testdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - PGDATA=/var/lib/postgresql/data/pgdata
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s